import { cn } from "@/utils/lib";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400"],
  subsets: ["latin"],
  variable: "--montserrat-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(montserrat.variable, "relative font-montserrat")}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
